# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "Feature/*", "Feature/*/*", "Refactor/*", "Refactor/*/*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
          
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Hi
        run: |
            echo "\
             _____          _    _____ _        ___      ___               
            |  __ \\        | |  / ____| |      | \\ \\    / (_)
            | |__) |__  ___| |_| (___ | |_ __ _| |\\ \\  / / _  _____      __
            |  ___/ _ \\/ __| __|\\___ \\| __/ _\` | __\\ \\/ / | |/ _ \\ \\ /\\ / /
            | |  | (_) \\__ \\ |_ ____) | || (_| | |_ \\  /  | |  __/\\ V  V /
            |_|   \\___/|___/\\__|_____/ \\__\\__,_|\\__| \\/   |_|\\___| \\_/\\_/  "
        shell: bash

      - name: Create TEST YML
        run: |
          cd ./src/test/resources
          touch ./application-test.yml
          echo "${{ secrets.TEST_YML }}" > ./application-test.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash

      - name: Test with Gradle
        run: ./gradlew test
